apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      color: blue
  template:
    metadata:
      labels:
        color: blue
    spec:
      containers:
      - name: web
        image: brian24/cicdtest:blue
        imagePullPolicy: Always
        resources:
          limits:
            memory: "32Mi"
            cpu: "200m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  type: LoadBalancer   
  selector:         
    color: blue
  ports:
  - protocol: TCP
    port: 80      
    targetPort: 80  
